/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects.$projectId'
import { Route as ProjectsProjectIdSiteRouteImport } from './routes/projects.$projectId.site'
import { Route as ProjectsProjectIdPostsRouteImport } from './routes/projects.$projectId.posts'
import { Route as ProjectsProjectIdHomeRouteImport } from './routes/projects.$projectId.home'
import { Route as ProjectsProjectIdHelpRouteImport } from './routes/projects.$projectId.help'
import { Route as ProjectsProjectIdAboutRouteImport } from './routes/projects.$projectId.about'
import { Route as ProjectsProjectIdPostsIndexRouteImport } from './routes/projects.$projectId.posts.index'
import { Route as ProjectsProjectIdPostsPostIdRouteImport } from './routes/projects.$projectId.posts.$postId'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdSiteRoute = ProjectsProjectIdSiteRouteImport.update({
  id: '/site',
  path: '/site',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const ProjectsProjectIdPostsRoute = ProjectsProjectIdPostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const ProjectsProjectIdHomeRoute = ProjectsProjectIdHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const ProjectsProjectIdHelpRoute = ProjectsProjectIdHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const ProjectsProjectIdAboutRoute = ProjectsProjectIdAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const ProjectsProjectIdPostsIndexRoute =
  ProjectsProjectIdPostsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProjectsProjectIdPostsRoute,
  } as any)
const ProjectsProjectIdPostsPostIdRoute =
  ProjectsProjectIdPostsPostIdRouteImport.update({
    id: '/$postId',
    path: '/$postId',
    getParentRoute: () => ProjectsProjectIdPostsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/welcome': typeof WelcomeRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/projects/$projectId/about': typeof ProjectsProjectIdAboutRoute
  '/projects/$projectId/help': typeof ProjectsProjectIdHelpRoute
  '/projects/$projectId/home': typeof ProjectsProjectIdHomeRoute
  '/projects/$projectId/posts': typeof ProjectsProjectIdPostsRouteWithChildren
  '/projects/$projectId/site': typeof ProjectsProjectIdSiteRoute
  '/projects/$projectId/posts/$postId': typeof ProjectsProjectIdPostsPostIdRoute
  '/projects/$projectId/posts/': typeof ProjectsProjectIdPostsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/welcome': typeof WelcomeRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/projects/$projectId/about': typeof ProjectsProjectIdAboutRoute
  '/projects/$projectId/help': typeof ProjectsProjectIdHelpRoute
  '/projects/$projectId/home': typeof ProjectsProjectIdHomeRoute
  '/projects/$projectId/site': typeof ProjectsProjectIdSiteRoute
  '/projects/$projectId/posts/$postId': typeof ProjectsProjectIdPostsPostIdRoute
  '/projects/$projectId/posts': typeof ProjectsProjectIdPostsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/welcome': typeof WelcomeRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/projects/$projectId/about': typeof ProjectsProjectIdAboutRoute
  '/projects/$projectId/help': typeof ProjectsProjectIdHelpRoute
  '/projects/$projectId/home': typeof ProjectsProjectIdHomeRoute
  '/projects/$projectId/posts': typeof ProjectsProjectIdPostsRouteWithChildren
  '/projects/$projectId/site': typeof ProjectsProjectIdSiteRoute
  '/projects/$projectId/posts/$postId': typeof ProjectsProjectIdPostsPostIdRoute
  '/projects/$projectId/posts/': typeof ProjectsProjectIdPostsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/welcome'
    | '/projects/$projectId'
    | '/projects/$projectId/about'
    | '/projects/$projectId/help'
    | '/projects/$projectId/home'
    | '/projects/$projectId/posts'
    | '/projects/$projectId/site'
    | '/projects/$projectId/posts/$postId'
    | '/projects/$projectId/posts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/welcome'
    | '/projects/$projectId'
    | '/projects/$projectId/about'
    | '/projects/$projectId/help'
    | '/projects/$projectId/home'
    | '/projects/$projectId/site'
    | '/projects/$projectId/posts/$postId'
    | '/projects/$projectId/posts'
  id:
    | '__root__'
    | '/'
    | '/welcome'
    | '/projects/$projectId'
    | '/projects/$projectId/about'
    | '/projects/$projectId/help'
    | '/projects/$projectId/home'
    | '/projects/$projectId/posts'
    | '/projects/$projectId/site'
    | '/projects/$projectId/posts/$postId'
    | '/projects/$projectId/posts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WelcomeRoute: typeof WelcomeRoute
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/site': {
      id: '/projects/$projectId/site'
      path: '/site'
      fullPath: '/projects/$projectId/site'
      preLoaderRoute: typeof ProjectsProjectIdSiteRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/posts': {
      id: '/projects/$projectId/posts'
      path: '/posts'
      fullPath: '/projects/$projectId/posts'
      preLoaderRoute: typeof ProjectsProjectIdPostsRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/home': {
      id: '/projects/$projectId/home'
      path: '/home'
      fullPath: '/projects/$projectId/home'
      preLoaderRoute: typeof ProjectsProjectIdHomeRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/help': {
      id: '/projects/$projectId/help'
      path: '/help'
      fullPath: '/projects/$projectId/help'
      preLoaderRoute: typeof ProjectsProjectIdHelpRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/about': {
      id: '/projects/$projectId/about'
      path: '/about'
      fullPath: '/projects/$projectId/about'
      preLoaderRoute: typeof ProjectsProjectIdAboutRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/posts/': {
      id: '/projects/$projectId/posts/'
      path: '/'
      fullPath: '/projects/$projectId/posts/'
      preLoaderRoute: typeof ProjectsProjectIdPostsIndexRouteImport
      parentRoute: typeof ProjectsProjectIdPostsRoute
    }
    '/projects/$projectId/posts/$postId': {
      id: '/projects/$projectId/posts/$postId'
      path: '/$postId'
      fullPath: '/projects/$projectId/posts/$postId'
      preLoaderRoute: typeof ProjectsProjectIdPostsPostIdRouteImport
      parentRoute: typeof ProjectsProjectIdPostsRoute
    }
  }
}

interface ProjectsProjectIdPostsRouteChildren {
  ProjectsProjectIdPostsPostIdRoute: typeof ProjectsProjectIdPostsPostIdRoute
  ProjectsProjectIdPostsIndexRoute: typeof ProjectsProjectIdPostsIndexRoute
}

const ProjectsProjectIdPostsRouteChildren: ProjectsProjectIdPostsRouteChildren =
  {
    ProjectsProjectIdPostsPostIdRoute: ProjectsProjectIdPostsPostIdRoute,
    ProjectsProjectIdPostsIndexRoute: ProjectsProjectIdPostsIndexRoute,
  }

const ProjectsProjectIdPostsRouteWithChildren =
  ProjectsProjectIdPostsRoute._addFileChildren(
    ProjectsProjectIdPostsRouteChildren,
  )

interface ProjectsProjectIdRouteChildren {
  ProjectsProjectIdAboutRoute: typeof ProjectsProjectIdAboutRoute
  ProjectsProjectIdHelpRoute: typeof ProjectsProjectIdHelpRoute
  ProjectsProjectIdHomeRoute: typeof ProjectsProjectIdHomeRoute
  ProjectsProjectIdPostsRoute: typeof ProjectsProjectIdPostsRouteWithChildren
  ProjectsProjectIdSiteRoute: typeof ProjectsProjectIdSiteRoute
}

const ProjectsProjectIdRouteChildren: ProjectsProjectIdRouteChildren = {
  ProjectsProjectIdAboutRoute: ProjectsProjectIdAboutRoute,
  ProjectsProjectIdHelpRoute: ProjectsProjectIdHelpRoute,
  ProjectsProjectIdHomeRoute: ProjectsProjectIdHomeRoute,
  ProjectsProjectIdPostsRoute: ProjectsProjectIdPostsRouteWithChildren,
  ProjectsProjectIdSiteRoute: ProjectsProjectIdSiteRoute,
}

const ProjectsProjectIdRouteWithChildren =
  ProjectsProjectIdRoute._addFileChildren(ProjectsProjectIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WelcomeRoute: WelcomeRoute,
  ProjectsProjectIdRoute: ProjectsProjectIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
