// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreatePost(arg1, arg2) {
  return window['go']['api']['App']['CreatePost'](arg1, arg2);
}

export function CreateProject(arg1, arg2) {
  return window['go']['api']['App']['CreateProject'](arg1, arg2);
}

export function CurrentProjectID() {
  return window['go']['api']['App']['CurrentProjectID']();
}

export function DeletePost(arg1, arg2) {
  return window['go']['api']['App']['DeletePost'](arg1, arg2);
}

export function DeleteProject(arg1) {
  return window['go']['api']['App']['DeleteProject'](arg1);
}

export function DeployVercel(arg1) {
  return window['go']['api']['App']['DeployVercel'](arg1);
}

export function DuplicateProject(arg1) {
  return window['go']['api']['App']['DuplicateProject'](arg1);
}

export function ExportProjectByID(arg1) {
  return window['go']['api']['App']['ExportProjectByID'](arg1);
}

export function GetSetting(arg1) {
  return window['go']['api']['App']['GetSetting'](arg1);
}

export function IsExportedProject(arg1) {
  return window['go']['api']['App']['IsExportedProject'](arg1);
}

export function ListPosts(arg1) {
  return window['go']['api']['App']['ListPosts'](arg1);
}

export function ListProjects() {
  return window['go']['api']['App']['ListProjects']();
}

export function ListTemplates() {
  return window['go']['api']['App']['ListTemplates']();
}

export function OpenFolder(arg1) {
  return window['go']['api']['App']['OpenFolder'](arg1);
}

export function OpenProject(arg1) {
  return window['go']['api']['App']['OpenProject'](arg1);
}

export function OpenURL(arg1) {
  return window['go']['api']['App']['OpenURL'](arg1);
}

export function PickExportDir(arg1) {
  return window['go']['api']['App']['PickExportDir'](arg1);
}

export function PreviewStatus() {
  return window['go']['api']['App']['PreviewStatus']();
}

export function ReadImage(arg1) {
  return window['go']['api']['App']['ReadImage'](arg1);
}

export function RenameProject(arg1, arg2) {
  return window['go']['api']['App']['RenameProject'](arg1, arg2);
}

export function ReorderPosts(arg1, arg2) {
  return window['go']['api']['App']['ReorderPosts'](arg1, arg2);
}

export function SaveProject(arg1) {
  return window['go']['api']['App']['SaveProject'](arg1);
}

export function SetCurrentProject(arg1) {
  return window['go']['api']['App']['SetCurrentProject'](arg1);
}

export function SetSetting(arg1, arg2) {
  return window['go']['api']['App']['SetSetting'](arg1, arg2);
}

export function StartPreview(arg1) {
  return window['go']['api']['App']['StartPreview'](arg1);
}

export function StopPreview() {
  return window['go']['api']['App']['StopPreview']();
}

export function Toolchain() {
  return window['go']['api']['App']['Toolchain']();
}

export function UpdatePost(arg1, arg2) {
  return window['go']['api']['App']['UpdatePost'](arg1, arg2);
}

export function UploadImage(arg1, arg2) {
  return window['go']['api']['App']['UploadImage'](arg1, arg2);
}
