// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';
import {api} from '../models';

export function CreatePost(arg1:string,arg2:domain.Post):Promise<domain.Post>;

export function CreateProject(arg1:string,arg2:string):Promise<domain.ProjectMeta>;

export function CurrentProjectID():Promise<string>;

export function DeletePost(arg1:string,arg2:string):Promise<void>;

export function DeleteProject(arg1:string):Promise<void>;

export function DeployVercel(arg1:string):Promise<string>;

export function DuplicateProject(arg1:string):Promise<domain.ProjectMeta>;

export function ExportProjectByID(arg1:domain.ExportRequest):Promise<domain.ExportResult>;

export function GetSetting(arg1:string):Promise<string>;

export function IsExportedProject(arg1:string):Promise<boolean>;

export function ListPosts(arg1:string):Promise<Array<domain.Post>>;

export function ListProjects():Promise<Array<domain.ProjectMeta>>;

export function ListTemplates():Promise<Array<domain.TemplateInfo>>;

export function OpenFolder(arg1:string):Promise<void>;

export function OpenProject(arg1:string):Promise<domain.Project>;

export function OpenURL(arg1:string):Promise<void>;

export function PickExportDir(arg1:string):Promise<string>;

export function PreviewStatus():Promise<api.PreviewState>;

export function ReadImage(arg1:string):Promise<string>;

export function RenameProject(arg1:string,arg2:string):Promise<void>;

export function ReorderPosts(arg1:string,arg2:Array<string>):Promise<void>;

export function SaveProject(arg1:domain.Project):Promise<void>;

export function SetCurrentProject(arg1:string):Promise<void>;

export function SetSetting(arg1:string,arg2:string):Promise<void>;

export function StartPreview(arg1:string):Promise<api.PreviewState>;

export function StopPreview():Promise<void>;

export function Toolchain():Promise<api.ToolchainInfo>;

export function UpdatePost(arg1:string,arg2:domain.Post):Promise<domain.Post>;

export function UploadImage(arg1:string,arg2:string):Promise<string>;
